name: Copy-to-specificaions

on:
  push:
    branches:
      - main

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in solution folder
        run: ls -l CI-CD-Test

      - name: List files in specifications folder before copy
        run: ls -l Specifications

      - name: Copy file to specifications
        run: cp CI-CD-Test/test.txt Specifications

      - name: List files in specifications folder after copy
        run: ls -l Specifications
